export * from "./login";
export * from "./main";
export * from "./grades";
export * from "./schedule";
export * from "./contact";
export * from "./subjects";
export * from "./teacher";
export * from "./students";
export * from "./dashboard";
